version: '3'

services: 
  app:
    image: abhinavsinha19/basic-express:0.1
    container_name: express-app
    restart: always
    ports: 
      - "8080:8080"
    environment:
      NODE_ENV: production