name: Build image on DockerHub and deploy to AWS EC2

on:
  push:
    branches:
    - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        dockerfile: ./Dockerfile
        tags: abhinavsinha19/basic-express:0.1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: SSH to EC2, and run docker container
      run: |
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > key && chmod 600 key
        ssh -o StrictHostKeyChecking=no -i key ec2-user@ec2-52-66-197-249.ap-south-1.compute.amazonaws.com

        sudo docker pull abhinavsinha19/basic-express:0.1 &&
        sudo docker stop basic-express || true &&
        sudo docker rm basic-express || true &&
        sudo docker run -d --name basic-express -p 8080:8080 abhinavsinha19/basic-express:0.1


    # - name: Pull Docker image
    #   run: |
    #     ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-52-66-197-249.ap-south-1.compute.amazonaws.com 'sudo docker pull abhinavsinha19/basic-express:0.1'

    # - name: Stop running container
    #   run: |
    #     ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-52-66-197-249.ap-south-1.compute.amazonaws.com 'sudo docker stop basic-express || true'

    #     ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-52-66-197-249.ap-south-1.compute.amazonaws.com 'sudo docker rm basic-express || true'

    # - name: Run new container
    #   run: |
    #     ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-52-66-197-249.ap-south-1.compute.amazonaws.com 'sudo docker run -d --name basic-express -p 8080:8080 abhinavsinha19/basic-express:0.1'
